-- 
CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100) UNIQUE NOT NULL,
  entries bigint DEFAULT 0,
  joined TIMESTAMP NOT NULL
);

-- 
CREATE TABLE login (
  id INTEGER PRIMARY KEY,
  hash VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL
);

--